### ISSUE TITLE
[BUG] LUA Error when the addon tries to pass (or hide) the Need/Greed window

### ISSUE THREAD

**Issue by Moowalker** [evil-morfar/RCLootCouncil2#227] opened 2022-12-28 19:23 UTC
**Describe the bug**
When the loot drops there is a LUA errror and the Need/Greed windows does not hide

`1x RCLootCouncil/Utils/popups.lua:169: bad argument #1 to 'Click' (Usage: self:Click([button, isDown]))
[string "=[C]"]: in function `Click'
[string "@RCLootCouncil/Utils/popups.lua"]:169: in function `on_cancel'
[string "@RCLootCouncil/Libs/LibDialog-1.0-9/LibDialog-1.0.lua"]:815: in function `Spawn'
[string "@RCLootCouncil/core.lua"]:562: in function `onFound'
[string "@RCLootCouncil/Utils/ItemStorage.lua"]:348: in function `func'
[string "@ElvUI_Libraries/Core/Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <...UI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
(*temporary) = LibDialog-1.0_Button2 {
 0 = <userdata>
}
(*temporary) = LibDialog-1.0_Dialog1 {
 BottomLeftCorner = Texture {
 }
 PixelSnapDisabled = true
 data = "|cffa335ee|Hitem:195487::::::::70:105::5:6:6652:8825:8820:7980:1485:8767::::::|h[Embar's Ashen Hauberk]|h|r"
 close_button = Button {
 }
 backdropInfo = <table> {
 }
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 buttons = <table> {
 }
 TopEdge = Texture {
 }
 BottomEdge = Texture {
 }
 icon2 = LibDialog-1.0_Dialog1RC_UI_Icon2 {
 }
 icon = LibDialog-1.0_Dialog1Icon {
 }
 0 = <userdata>
 delegate = <table> {
 }
 Center = Texture {
 }
 BottomRightCorner = Texture {
 }
 LeftEdge = Texture {
 }
 text = FontString {
 }
}
(*temporary) = "|cffa335ee|Hitem:195487::::::::70:105::5:6:6652:8825:8820:7980:1485:8767::::::|h[Embar's Ashen Hauberk]|h|r"
`

**Comment by evil-morfar** [comment] 2022-12-28 22:24
The error is caused by pressing escape with the "Keep or trade" pop-up open - that will be fixed next update - but it's not related to what you're describing. You should have attached your saved variables.

**Comment by Moowalker** [comment] 2022-12-28 22:31
[RCLootCouncil.zip](https://github.com/evil-morfar/RCLootCouncil2/files/10316726/RCLootCouncil.zip)

Yes, you are correct. I made it during our raid and I wanted to fill it up later but I pressed "Submit" by mistake. I did not press escape at all, just as the boss died, the loot Need / Greed popup up and then the LUA error popped (that happened on everyboss).

I am using v3.6.5.

**Comment by evil-morfar** [comment] 2022-12-28 23:51
I see you figured out to use `/rc add` - awesome.
There's a ton of errors listed in your file, so it's gonna take a while for me to sift through them.

Just so we're on the same page, it's the default group loot roll frame you're talking about not disappearing, right? Any other issues?

I found one instance where you're having an issue similar to others with the addon not being activated properly - when entering the raid (or when creating the group) you should have gotten the usage pop-up, did you? Also note it will always print "Now handles looting" when activated, and if it don't somethings wrong. You can manually activate it with `/rc start`.

**Comment by Moowalker** [comment] 2022-12-29 08:13
First, about the group loot frame (with the need /greed buttons) just pops up (the addon auto greeds correctly) but then it stays up. By loot windows I mean the blizzard frame not the RC one. If I reload UI everything it goes away.

About the addon not being active, when I enter the raid it pops up if I want to use the addon, but if I reload UI it deactivates, so I am actually doing ``/rc start``  every time I reload my UI.

**Comment by evil-morfar** [comment] 2022-12-29 20:19
Yeah I found the bug causing reloads to not prompt for usage again - it's fixed with v3.6.6. Still not sure why the loot frame stays.

**Closed** 2023-04-13 15:34 UTC
Labels: bug
